variable "client_name" {}
variable "project_name" {}
variable "env" {}
variable "location" {}
variable "deployer_object_id" {}
variable "tenant_id" {}
variable "deployer_ip_address" {}
variable "deploy_networking" {}
variable "deploy_data_factory" {}
variable "deploy_synapse" {}
variable "deploy_databricks" {}
variable "deploy_purview" {}